version: "3.3"

services:
  app:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      DATABASE_HOSTNAME: 'db'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: ''
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
